//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.SWMiravalle {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWMiravalle.ServicioNotificacionSoap")]
    public interface ServicioNotificacionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotificarProductosVencidos", ReplyAction="*")]
        void NotificarProductosVencidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotificarProductosVencidos", ReplyAction="*")]
        System.Threading.Tasks.Task NotificarProductosVencidosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioNotificacionSoapChannel : Web.SWMiravalle.ServicioNotificacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioNotificacionSoapClient : System.ServiceModel.ClientBase<Web.SWMiravalle.ServicioNotificacionSoap>, Web.SWMiravalle.ServicioNotificacionSoap {
        
        public ServicioNotificacionSoapClient() {
        }
        
        public ServicioNotificacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioNotificacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNotificacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNotificacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NotificarProductosVencidos() {
            base.Channel.NotificarProductosVencidos();
        }
        
        public System.Threading.Tasks.Task NotificarProductosVencidosAsync() {
            return base.Channel.NotificarProductosVencidosAsync();
        }
    }
}
