//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Web.SWMiravalle {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioNotificacionSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioNotificacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NotificarProductosVencidosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioNotificacion() {
            this.Url = global::Web.Properties.Settings.Default.Web_SWMiravalle_ServicioNotificacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NotificarProductosVencidosCompletedEventHandler NotificarProductosVencidosCompleted;
        
        /// <remarks/>
        public event ConsultarProductoCompletedEventHandler ConsultarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificarProductosVencidos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NotificarProductosVencidos() {
            this.Invoke("NotificarProductosVencidos", new object[0]);
        }
        
        /// <remarks/>
        public void NotificarProductosVencidosAsync() {
            this.NotificarProductosVencidosAsync(null);
        }
        
        /// <remarks/>
        public void NotificarProductosVencidosAsync(object userState) {
            if ((this.NotificarProductosVencidosOperationCompleted == null)) {
                this.NotificarProductosVencidosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificarProductosVencidosOperationCompleted);
            }
            this.InvokeAsync("NotificarProductosVencidos", new object[0], this.NotificarProductosVencidosOperationCompleted, userState);
        }
        
        private void OnNotificarProductosVencidosOperationCompleted(object arg) {
            if ((this.NotificarProductosVencidosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificarProductosVencidosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoDTO[] ConsultarProducto(string Nombre, int IdTipoProducto, int IdProducto) {
            object[] results = this.Invoke("ConsultarProducto", new object[] {
                        Nombre,
                        IdTipoProducto,
                        IdProducto});
            return ((ProductoDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarProductoAsync(string Nombre, int IdTipoProducto, int IdProducto) {
            this.ConsultarProductoAsync(Nombre, IdTipoProducto, IdProducto, null);
        }
        
        /// <remarks/>
        public void ConsultarProductoAsync(string Nombre, int IdTipoProducto, int IdProducto, object userState) {
            if ((this.ConsultarProductoOperationCompleted == null)) {
                this.ConsultarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarProductoOperationCompleted);
            }
            this.InvokeAsync("ConsultarProducto", new object[] {
                        Nombre,
                        IdTipoProducto,
                        IdProducto}, this.ConsultarProductoOperationCompleted, userState);
        }
        
        private void OnConsultarProductoOperationCompleted(object arg) {
            if ((this.ConsultarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarProductoCompleted(this, new ConsultarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoDTO {
        
        private string nombreproductoField;
        
        private int idproductoField;
        
        private TipoProductoDTO tipoField;
        
        /// <remarks/>
        public string nombreproducto {
            get {
                return this.nombreproductoField;
            }
            set {
                this.nombreproductoField = value;
            }
        }
        
        /// <remarks/>
        public int idproducto {
            get {
                return this.idproductoField;
            }
            set {
                this.idproductoField = value;
            }
        }
        
        /// <remarks/>
        public TipoProductoDTO tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoProductoDTO {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotificarProductosVencidosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarProductoCompletedEventHandler(object sender, ConsultarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoDTO[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591